export const actionTypes = {
    ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAILED: 'ORDER_CREATE_FAILED',

    
    ORDER_DETAIL_REQUEST: 'ORDER_DETAIL_REQUEST',
    ORDER_DETAIL_SUCCESS: 'ORDER_DETAIL_SUCCESS',
    ORDER_DETAIL_FAILED: 'ORDER_DETAIL_FAILED',

    ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
    ORDER_PAY_FAILED: 'ORDER_PAY_FAILED',
    ORDER_PAY_RESET: 'ORDER_PAY_RESET',

    ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
    ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',
    ORDER_LIST_FAILED: 'ORDER_LIST_FAILED',

    ORDER_DELIVER_REQUEST: 'ORDER_DELIVER_REQUEST',
    ORDER_DELIVER_SUCCESS: 'ORDER_DELIVER_SUCCESS',
    ORDER_DELIVER_FAILED: 'ORDER_DELIVER_FAILED',
    ORDER_DELIVER_RESET: 'ORDER_DELIVER_RESET',

    
    
}