export const actionType = {

    PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
    PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_FAILED: 'PRODUCT_CREATE_FAILED',

    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAILED: 'PRODUCT_LIST_FAILED',

    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAILED: 'PRODUCT_DETAIL_FAILED',

    PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
    PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_FAILED: 'PRODUCT_UPDATE_FAILED',

    PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAILED: 'PRODUCT_DELETE_FAILED',

    PRODUCT_REVIEW_CREATE_REQUEST: 'PRODUCT_REVIEW_CREATE_REQUEST',
    PRODUCT_REVIEW_CREATE_SUCCESS: 'PRODUCT_REVIEW_CREATE_SUCCESS',
    PRODUCT_REVIEW_CREATE_FAILED: 'PRODUCT_REVIEW_CREATE_FAILED',
    PRODUCT_REVIEW_CREATE_RESET: 'PRODUCT_REVIEW_CREATE_RESET',
    
    TOP_PRODUCT_REQUEST: 'TOP_PRODUCT_REQUEST',
    TOP_PRODUCT_SUCCESS: 'TOP_PRODUCT_SUCCESS',
    TOP_PRODUCT_FAILED: 'TOP_PRODUCT_FAILED',
    


}